sudo: false
dist: bionic
addons:
    apt:
        packages:
            - python
            - python3-dev
            - python-pip
            - python-virtualenv
            - protobuf-compiler

language: cpp

matrix:
    include:
        - compiler: gcc
          env: BUILD_TYPE="tests"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="master-firmware"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="motor-control-firmware"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="can-io-firmware"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="proximity-beacon-firmware"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="uwb-beacon-firmware"

before_install:
    - git submodule update --init --recursive

install:
    - ci/install.sh

script:
    - ci/build.sh
