logging:
  # level can be "debug", "notice" "warning" or "error"
  uart:
    level: "notice"
  sdcard:
    level: "notice" # changing this to debug slows down things too much and causes panic
ip:
  ethernet:
    address: "192.168.3.20"
    netmask: "255.255.255.0"
  uwb:
    address: "10.0.0.10"
    netmask: "255.255.255.0"
  ally_address: "10.0.0.20"
master:
    is_main_robot: false
    control_panel_active_high: true
    electron_uwb_mac: 42
    robot_size_x_mm: 260 # Robot diameter
    robot_alignment_length_mm: 135 # robot length from center to alignement border
    opponent_size_x_mm_default: 400
    calibration_direction: 1 # calibration side is on the front
    odometry:
        external_encoder_ticks_per_mm: 162.974661726 # Computed 162.974661726
        external_track_mm: 201.329696655
        left_wheel_correction_factor: -0.99942505
        right_wheel_correction_factor: 1.00057482
    beacon:
        reflector_radius: 0.04 # in meters
        angular_offset: 1.57 # in radians
    aversive:
        control:
            angle:
                kp: 1.5
                ki: 0.5
                kd: 10.
                i_limit: 10.
            distance:
                kp: 1.5
                ki: 0.5
                kd: 10.
                i_limit: 10.
        trajectories:
            angle:
                speed: # in rad / s
                    init: 0.75
                    slow: 0.75
                    fast: 3.
                acceleration: # in rad / s^2
                    init: 1.57
                    slow: 1.57
                    fast: 10.
            distance:
                speed: # in m / s
                    init: 0.1
                    slow: 0.2
                    fast: 0.5
                acceleration: # in m / s^2
                    init: 0.15
                    slow: 0.5
                    fast: 1.5
            windows:
                distance: 100.
                angle: 40.
                angle_start: 40.
    arms:
        right:
            lengths:
                origin: 0.2428
                l1: 0.132
                l2: 0.097
                l3: 0.072
            homing:
                q1: -0.40763
                q2: 1.53969
                q3: 0.0
            offsets: # calibrated before a game
                q1: 0.
                q2: 0.
                q3: 0.
            tolerance:
                q1: 0.02
                q2: 0.02
                q3: 0.02
            window:
                q1: 0.1
                q2: 0.1
                q3: 0.1
            gripper:
                release: -6.
                acquire: 14.
                current_thres: 0.3 # [A] pump current beyond which we consider the puck is picked
        left:
            lengths:
                origin: 0.2428
                l1: 0.132
                l2: 0.097
                l3: 0.072
            homing:
                q1: -0.40763
                q2: 1.53969
                q3: 0.0
            offsets: # calibrated before a game
                q1: 0.
                q2: 0.
                q3: 0.
            tolerance:
                q1: 0.02
                q2: 0.02
                q3: 0.02
            window:
                q1: 0.1
                q2: 0.1
                q3: 0.1
            gripper:
                release: -6.
                acquire: 14.
                current_thres: 0.3 # [A] pump current beyond which we consider the puck is picked
    screen:
        ax: 0.089231252
        ay: -0.001139728
        bx: 0.000522375
        by: 0.127720847
        cx: -22.532257080
        cy: -28.272106170

actuator:
    left-wheel:
        encoders:
          primary:
            p: 49
            q: 676
            ticks_per_rev: 4096
        motor:
            torque_cst: 1.
        control:
            mode: 2
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                i_limit: 50.
            velocity:
                kp: 20.
                ki: 50.
                kd: 0.
                i_limit: 1000.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.
            low_batt_th: 5.
            acceleration_limit: 200.
            velocity_limit: 50.
            torque_limit: 30.
    right-wheel:
        encoders:
          primary:
            p: 49
            q: 676
            ticks_per_rev: 4096
        motor:
            torque_cst: 1.
        control:
            mode: 2
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                i_limit: 50.
            velocity:
                kp: 20.
                ki: 50.
                kd: 0.
                i_limit: 1000.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.

            low_batt_th: 5.
            acceleration_limit: 200.
            velocity_limit: 50.
            torque_limit: 30.
    right-theta-1:
    # motor: 2232 U009 SR
        streams:
            motor_pos: 50.
            current: 20.
            velocity: 20.
            position: 20.
        encoders:
            primary:
                ticks_per_rev: 4096
                # transmission: motor: 175/14976 x gears: 1/3
                p: 1 # 175
                q: 257 # 44928
        motor:
            current_offset: 0
            torque_cst: 2.952 # Nm/A after transmission, before 0.0115, datasheet: 11.5 mNm/A
        control:
            acceleration_limit: 20 # rad/s^2
            velocity_limit: 3.14 # rad/s
            torque_limit: 2.6 # Nm after transmission, before 0.0100, datasheet: 10.0 mNm
            mode: 3 # bounded
            low_batt_th: 5.
            current:
                i_limit: 50.0
                kd: 0.0
                ki: 600.0
                kp: 2.0
            position:
                i_limit: 1000.0
                kd: 0.0
                ki: 1.0
                kp: 50.0
            velocity:
                i_limit: 100.0
                kd: 0.0
                ki: 2.0
                kp: 30
    right-theta-2:
    # motor: 2232 U009 SR
        streams:
            motor_pos: 50.
            current: 20.
            velocity: 20.
            position: 20.
        encoders:
            primary:
                ticks_per_rev: 4096
                # transmission: motor: 175/14976 x gears: 1/3
                p: 1 # 175
                q: 257 # 44928
        motor:
            current_offset: 0
            torque_cst: 2.952 # Nm/A after transmission, before 0.0115, datasheet: 11.5 mNm/A
        control:
            acceleration_limit: 20 # rad/s^2
            velocity_limit: 3.14 # rad/s
            torque_limit: 2.6 # Nm after transmission, before 0.0100, datasheet: 10.0 mNm
            mode: 3 # bounded
            low_batt_th: 5.
            current:
                i_limit: 50.0
                kd: 0.0
                ki: 600.0
                kp: 2.0
            position:
                i_limit: 1000.0
                kd: 0.0
                ki: 1.0
                kp: 25.0
            velocity:
                i_limit: 1.0
                kd: 0.0
                ki: 4.0
                kp: 20.0
    right-theta-3:
    # motor: 1524 U012 SR
        streams:
            motor_pos: 50.
            current: 20.
            velocity: 20.
            position: 20.
        encoders:
            primary:
                ticks_per_rev: 4096
                # transmission: motor: 5103/387283 x gears: 1/3
                p: 1 # 1701
                q: 228 # 387283
        motor:
            current_offset: 0
            torque_cst: 2.618 # Nm/A after transmission, before 0.0115, datasheet: 11.5 mNm/A
        control:
            acceleration_limit: 20 # rad/s^2
            velocity_limit: 3.14 # rad/s
            torque_limit: 0.7 # Nm after transmission, before 0.0029, datasheet: 2.9 mNm
            mode: 3 # bounded
            low_batt_th: 5.
            current:
                i_limit: 50.0
                kd: 0.0
                ki: 700.0
                kp: 5.0
            position:
                i_limit: 100.0
                kd: 5.0
                ki: 10.0
                kp: 200.0
            velocity:
                i_limit: 10.0
                kd: 0.0
                ki: 0.1
                kp: 25.0
    right-pump-1:
        control:
            mode: 0 # openloop
            low_batt_th: 5.
        streams:
            current: 10
    right-pump-2:
        control:
            mode: 0 # openloop
            low_batt_th: 5.
        streams:
            current: 10
    left-theta-1:
    # motor: 2232 U009 SR
        streams:
            motor_pos: 50.
            current: 20.
            velocity: 20.
            position: 20.
        encoders:
            primary:
                ticks_per_rev: 4096
                # transmission: motor: 175/14976 x gears: 1/3
                p: 1 # 175
                q: 257 # 44928
        motor:
            current_offset: 0
            torque_cst: 2.952 # Nm/A after transmission, before 0.0115, datasheet: 11.5 mNm/A
        control:
            acceleration_limit: 20 # rad/s^2
            velocity_limit: 3.14 # rad/s
            torque_limit: 2.6 # Nm after transmission, before 0.0100, datasheet: 10.0 mNm
            mode: 3 # bounded
            low_batt_th: 5.
            current:
                i_limit: 50.0
                kd: 0.0
                ki: 600.0
                kp: 2.0
            position:
                i_limit: 1000.0
                kd: 0.0
                ki: 1.0
                kp: 50.0
            velocity:
                i_limit: 100.0
                kd: 0.0
                ki: 2.0
                kp: 30
    left-theta-2:
    # motor: 2232 U009 SR
        streams:
            motor_pos: 50.
            current: 20.
            velocity: 20.
            position: 20.
        encoders:
            primary:
                ticks_per_rev: 4096
                # transmission: motor: 175/14976 x gears: 1/3
                p: 1 # 175
                q: 257 # 44928
        motor:
            current_offset: 0
            torque_cst: 2.952 # Nm/A after transmission, before 0.0115, datasheet: 11.5 mNm/A
        control:
            acceleration_limit: 20 # rad/s^2
            velocity_limit: 3.14 # rad/s
            torque_limit: 2.6 # Nm after transmission, before 0.0100, datasheet: 10.0 mNm
            mode: 3 # bounded
            low_batt_th: 5.
            current:
                i_limit: 50.0
                kd: 0.0
                ki: 600.0
                kp: 2.0
            position:
                i_limit: 1000.0
                kd: 0.0
                ki: 1.0
                kp: 25.0
            velocity:
                i_limit: 1.0
                kd: 0.0
                ki: 4.0
                kp: 20.0
    left-theta-3:
    # motor: 1524 U012 SR
        streams:
            motor_pos: 50.
            current: 20.
            velocity: 20.
            position: 20.
        encoders:
            primary:
                ticks_per_rev: 2048
                # transmission: motor: 5103/387283 x gears: 1/3
                p: 1 # 1701
                q: 228 # 387283
        motor:
            current_offset: 0
            torque_cst: 2.618 # Nm/A after transmission, before 0.0115, datasheet: 11.5 mNm/A
        control:
            acceleration_limit: 20 # rad/s^2
            velocity_limit: 3.14 # rad/s
            torque_limit: 0.7 # Nm after transmission, before 0.0029, datasheet: 2.9 mNm
            mode: 3 # bounded
            low_batt_th: 5.
            current:
                i_limit: 50.0
                kd: 0.0
                ki: 700.0
                kp: 5.0
            position:
                i_limit: 100.0
                kd: 5.0
                ki: 10.0
                kp: 200.0
            velocity:
                i_limit: 10.0
                kd: 0.0
                ki: 0.1
                kp: 25.0
    left-pump-1:
        control:
            mode: 0 # openloop
            low_batt_th: 5.
        streams:
            current: 10
    left-pump-2:
        control:
            mode: 0 # openloop
            low_batt_th: 5.
        streams:
            current: 10
