
actuator:
    right-z:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 0
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 4096
            # transmission: motor: 1/1 gears: 16/42
            transmission_ratio_p: 8
            transmission_ratio_q: 21
            torque_constant: 0.016 # Nm/A
        control:
            current:
                kp: 30.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 0.5
                ki: 0.8
                kd: 0.
                ilimit: 0.13
            position:
                kp: 6
                ki: 1.
                kd: 2.

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 8.
            torque_limit: 1.3
