master:
    foo: 10.
    odometry:
        wheelbase: 0.194
        radius_left: 0.016
        radius_right: 0.016

slaves:
    10:
        pid:
            current:
                kp: 5.
                ki: 1000.
                kd: 0.
                ilimit: 50.

            speed:
                kp: 0.4
                ki: 40.
                kd: 0.
                ilimit: 100.

    11:
        pid:
            current:
                kp: 5.
                ki: 1000.
                kd: 0.
                ilimit: 50.

            speed:
                kp: 0.4
                ki: 40.
                kd: 0.
                ilimit: 100.
