master:
    robot_size_x_mm: 205 # Front to back length
    opponent_size_x_mm_default: 300
    calibration_direction: 1 # calibration side is on the front
    odometry:
        external_encoder_ticks_per_mm: 162.974661726 # Computed 162.974661726
        external_track_mm: 193.50199890              # CAD 194
        left_wheel_correction_factor: -1.00028944
        right_wheel_correction_factor: 0.99971050
    beacon:
        reflector_radius: 0.04 # in meters
        angular_offset: -1.57 # in radians
    aversive:
        control:
            angle:
                kp: 50.
                ki: 0.
                kd: 0.
                ilimit: 1000.
            distance:
                kp: 50.
                ki: 0.
                kd: 0.
                ilimit: 5000.
    arms:
        upperarm_length: 140. # in mm
        forearm_length: 72. # in mm
        left:
            offset_x: 0.   # in mm
            offset_y: 120. # in mm
            offset_a: 1.57 # in radians
        right:
            offset_x: 0.   # in mm
            offset_y: -120. # in mm
            offset_a: -1.57 # in radians

actuator:
    left-wheel:
        stream:
            # Encoder position is needed for odometry
            encoder_pos: 0
            velocity_pid: 0
            position_pid: 0
        motor:
            mode: 2
            motor_encoder_steps_per_revolution: 4096
            second_encoder_steps_per_revolution: 16384
            transmission_ratio_p: 49
            transmission_ratio_q: 676
            torque_constant: 1.
        control:
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                ilimit: 50.

            velocity:
                kp: 14.
                ki: 110.
                kd: 0.
                ilimit: 1400.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.

            low_batt_th: 5.
            acceleration_limit: 100.
            velocity_limit: 50.
            torque_limit: 14.

    right-wheel:
        stream:
            # Encoder position is needed for odometry
            encoder_pos: 0
            velocity_pid: 0
            position_pid: 0
        motor:
            mode: 2
            motor_encoder_steps_per_revolution: 4096
            second_encoder_steps_per_revolution: 16384
            transmission_ratio_p: 49
            transmission_ratio_q: 676
            torque_constant: 1.
        control:
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                ilimit: 50.
            velocity:
                kp: 14.
                ki: 110.
                kd: 0.
                ilimit: 1400.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.

            low_batt_th: 5.
            acceleration_limit: 100.
            velocity_limit: 50.
            torque_limit: 14.

    left-shoulder:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 5
            index: 10
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/80
            transmission_ratio_p: 1
            transmission_ratio_q: 304
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 0.2
                ki: 0.8
                kd: 0.
                ilimit: 0.13
            position:
                kp: 6
                ki: 1.
                kd: 2.

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 1.
            torque_limit: 1

    left-elbow:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 5
            index: 10
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/60
            transmission_ratio_p: 1
            transmission_ratio_q: 228
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 8
                ki: 1
                kd: 0.
                ilimit: 0.5
            position:
                kp: 12
                ki: 0.
                kd: 0.

            low_batt_th: 12
            acceleration_limit: 20.
            velocity_limit: 5.
            torque_limit: 3

    right-shoulder:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 5
            index: 10
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/80
            transmission_ratio_p: 1
            transmission_ratio_q: 304
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 0.2
                ki: 0.8
                kd: 0.
                ilimit: 0.13
            position:
                kp: 6
                ki: 1.
                kd: 2.

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 1.
            torque_limit: 1

    right-elbow:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 5
            index: 10
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/60
            transmission_ratio_p: 1
            transmission_ratio_q: 228
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 8
                ki: 1
                kd: 0.
                ilimit: 0.5
            position:
                kp: 12
                ki: 0.
                kd: 0.

            low_batt_th: 12
            acceleration_limit: 20.
            velocity_limit: 5.
            torque_limit: 3
